name: CI with SonarQube

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1.0.0
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: "http://50.16.118.212:9000"
        with:
       
         args: >
          -Dsonar.projectKey=my-react-app
          -Dsonar.sources=.
         





